#!/usr/bin/env python
import sys
import pyRRG
import argparse

parser = argparse.ArgumentParser("pyRRG")
parser.add_argument("filename", help="Input Filename", type=str)
parser.add_argument('--version', action='version', version=pyRRG.__version__)
args = parser.parse_args()

pyRRG.main(args.filename)
